const KEY='workoutPlannerV1'; let exercises=[],state=load(),tab='today',draft=null;
function load(){try{return JSON.parse(localStorage.getItem(KEY))||{sessions:[],prefs:{level:0}}}catch{return{sessions:[],prefs:{level:0}}}}
function save(){localStorage.setItem(KEY,JSON.stringify(state))} const $=s=>document.querySelector(s);
const levelRank=x=>({Beginner:0,Intermediate:1,Advanced:2}[x]??0); const equip=x=>({FW:'Free Weight',C:'Cable',M:'Machine'}[x]||x);
function matches(ex,t){if(t==='Push')return ex.function==='Push'&&ex.region!=='Lower';if(t==='Pull')return ex.function==='Pull'&&ex.region!=='Lower';if(t==='Legs')return ex.region==='Lower';if(t==='Core')return ex.region==='Core';return ex.muscleGroup===t}
function lastEntries(id){return state.sessions.filter(s=>s.completed).sort((a,b)=>b.date.localeCompare(a.date)).flatMap(s=>s.entries.filter(e=>e.exerciseID===id).map(e=>({...e,date:s.date}))) }
function isBodyweight(ex){const n=(ex.name+' '+ex.muscleGroup).toLowerCase();return ex.region==='Core'||/(push.?up|pull.?up|chin.?up|dip|plank|crunch|sit.?up|body.?weight|burpee|mountain climber|leg raise|knee raise|hip thrust|glute bridge|bridge|superman|inverted row|air squat|wall sit|lunge|step.?up|calf raise)/i.test(n)}
function previousText(id){const e=lastEntries(id)[0];if(!e||!e.sets?.length)return'';const ex=exercises.find(x=>x.id===id),bw=isBodyweight(ex);return e.sets.map(s=>bw?`${s.reps} reps`:`${s.weight} lb × ${s.reps}`).join(' • ')}
function suggestion(id){const e=lastEntries(id)[0];if(!e||!e.sets?.length)return{weight:0,sets:3,reps:8};const w=Math.max(...e.sets.map(s=>+s.weight||0)),rs=e.sets.map(s=>+s.reps||0),ok=rs.length>=3&&rs.every(r=>r>=8),inc=w<40?2.5:w<100?5:10;return{weight:ok?w+inc:w,sets:Math.max(3,e.sets.length),reps:ok?8:Math.max(8,Math.round(rs.reduce((a,b)=>a+b,0)/rs.length))}}
function generate(t,count=6){const now=Date.now(),usage={},last={};state.sessions.filter(s=>s.completed).forEach(s=>s.entries.forEach(e=>{usage[e.exerciseID]=(usage[e.exerciseID]||0)+1;last[e.exerciseID]=Math.max(last[e.exerciseID]||0,new Date(s.date).getTime())}));const lvl=Math.min(2,Math.floor(state.sessions.filter(s=>s.completed).length/8));return exercises.filter(e=>matches(e,t)).map(e=>{const days=last[e.id]?Math.min(30,(now-last[e.id])/86400000):30;let score=100+Math.min(days,21)*2.5-(usage[e.id]||0)*2-Math.abs(levelRank(e.level)-lvl)*14+(e.joint==='M'?4:0)+(Math.random()*16-8);return{e,score}}).sort((a,b)=>b.score-a.score).slice(0,count).map(x=>x.e)}
function recommended(){const recent=state.sessions.filter(s=>s.completed).sort((a,b)=>b.date.localeCompare(a.date))[0];if(!recent)return'Push';const regs=recent.entries.map(e=>exercises.find(x=>x.id===e.exerciseID)).filter(Boolean);if(regs.some(x=>x.region==='Lower'))return'Pull';if(regs.some(x=>x.function==='Push'&&x.region!=='Lower'))return'Pull';if(regs.some(x=>x.function==='Pull'&&x.region!=='Lower'))return'Legs';return'Push'}
function scorePool(pool,count,used=new Set()){const now=Date.now(),usage={},last={};state.sessions.filter(s=>s.completed).forEach(s=>s.entries.forEach(e=>{usage[e.exerciseID]=(usage[e.exerciseID]||0)+1;last[e.exerciseID]=Math.max(last[e.exerciseID]||0,new Date(s.date).getTime())}));const lvl=Math.min(2,Math.floor(state.sessions.filter(s=>s.completed).length/8));return pool.filter(e=>!used.has(e.id)).map(e=>{const days=last[e.id]?Math.min(30,(now-last[e.id])/86400000):30;const score=100+Math.min(days,21)*2.5-(usage[e.id]||0)*2-Math.abs(levelRank(e.level)-lvl)*14+(e.joint==='M'?4:0)+(Math.random()*16-8);return{e,score}}).sort((a,b)=>b.score-a.score).slice(0,count).map(x=>x.e)}
function generateFullBody(){const used=new Set(),out=[];const take=(filter,count)=>{for(const e of scorePool(exercises.filter(filter),count,used)){out.push(e);used.add(e.id)}};take(e=>e.region==='Lower'&&e.joint==='M',1);take(e=>e.region==='Upper'&&e.function==='Push',1);take(e=>e.region==='Upper'&&e.function==='Pull',1);take(e=>e.region==='Lower',1);take(e=>e.region==='Core',1);const recent=state.sessions.filter(s=>s.completed).sort((a,b)=>b.date.localeCompare(a.date))[0];const recentGroups=new Set((recent?.entries||[]).map(x=>exercises.find(e=>e.id===x.exerciseID)?.muscleGroup).filter(Boolean));take(e=>e.region!=='Core'&&!recentGroups.has(e.muscleGroup),1);if(out.length<6)take(()=>true,6-out.length);return out.slice(0,6)}
function beginRAW(target,list){draft={target,date:new Date().toISOString(),entries:list.map(e=>{const s=suggestion(e.id);return{exerciseID:e.id,sets:Array.from({length:s.sets},(_,i)=>({setNumber:i+1,weight:isBodyweight(e)?0:s.weight,reps:s.reps}))}})};renderToday()}
function start(target){beginRAW(target,generate(target))}
function startFullBody(){beginRAW('Full Body',generateFullBody())}
function finish(){if(!draft)return;state.sessions.push({...draft,completed:true});save();draft=null;renderToday()}
function cancelRAW(){if(!draft)return;if(!confirm('Cancel this RAW? Everything entered in this session will be discarded.'))return;draft=null;renderToday()}
function render(){document.querySelectorAll('.tabs button').forEach(b=>b.classList.toggle('active',b.dataset.tab===tab));({today:renderToday,history:renderHistory,progress:renderProgress,library:renderLibrary}[tab])()}
function swapExercise(idx){if(!draft)return;const current=exercises.find(x=>x.id===draft.entries[idx].exerciseID),used=new Set(draft.entries.map(e=>e.exerciseID));let pool=exercises.filter(e=>!used.has(e.id)&&((current&&e.muscleGroup===current.muscleGroup)||matches(e,draft.target)));if(!pool.length)pool=exercises.filter(e=>!used.has(e.id)&&matches(e,draft.target));if(!pool.length)return;const replacement=pool[Math.floor(Math.random()*pool.length)],sg=suggestion(replacement.id);draft.entries[idx]={exerciseID:replacement.id,sets:Array.from({length:sg.sets},(_,i)=>({setNumber:i+1,weight:isBodyweight(replacement)?0:sg.weight,reps:sg.reps}))};renderToday()}
function removeExercise(idx){if(!draft)return;draft.entries.splice(idx,1);renderToday()}
function renderToday(){const app=$('#app');if(draft){app.innerHTML=`<div class="card hero"><div class="eyebrow">${draft.target} RAW</div><div class="heroTitle">Get RAW</div><p>${draft.entries.length} exercises • Log each completed set.</p></div><div class="card" id="work"></div><div class="finishActions"><button class="primary" id="finish">Finish RAW</button><button class="cancelRAW" id="cancelRAW">Cancel RAW</button></div>`;const w=$('#work');draft.entries.forEach((en,idx)=>{const ex=exercises.find(x=>x.id===en.exerciseID),prev=previousText(ex.id),bw=isBodyweight(ex);if(bw)en.sets.forEach(s=>s.weight=0);const d=document.createElement('div');d.className='exercise';d.innerHTML=`<div class="row"><div class="grow"><div class="exerciseTitle">${idx+1}. ${ex.name}</div><div class="muted">${ex.muscleGroup} • ${bw?'Bodyweight / reps':equip(ex.modality)} • ${ex.level}</div></div></div>${prev?`<div class="previous"><strong>Previous:</strong> ${prev}</div>`:''}<div class="sets"></div><div class="actionRow"><button class="small swap">Swap</button><button class="small danger remove">Remove</button></div>`;d.querySelector('.sets').innerHTML=en.sets.map((s,i)=>bw?`<div class="setrow repsonly"><span>Set ${i+1}</span><input inputmode="numeric" aria-label="reps" data-i="${idx}" data-s="${i}" data-k="reps" value="${s.reps||''}" placeholder="reps"></div>`:`<div class="setrow"><span>Set ${i+1}</span><input inputmode="decimal" aria-label="weight" data-i="${idx}" data-s="${i}" data-k="weight" value="${s.weight||''}" placeholder="lb"><input inputmode="numeric" aria-label="reps" data-i="${idx}" data-s="${i}" data-k="reps" value="${s.reps||''}" placeholder="reps"></div>`).join('');d.querySelector('.swap').onclick=()=>swapExercise(idx);d.querySelector('.remove').onclick=()=>removeExercise(idx);w.appendChild(d)});w.querySelectorAll('input').forEach(i=>i.addEventListener('input',e=>{const x=e.target;draft.entries[+x.dataset.i].sets[+x.dataset.s][x.dataset.k]=Math.max(0,+x.value||0)}));$('#finish').onclick=finish;$('#cancelRAW').onclick=cancelRAW;return}
const rec=recommended(),muscles=[...new Set(exercises.map(e=>e.muscleGroup))].sort(),done=state.sessions.filter(s=>s.completed);app.innerHTML=`<div class="card hero"><div class="eyebrow">Up Next</div><div class="heroTitle">${rec}</div><p>${done.length?`Your next session is based on ${done.length} completed RAW${done.length===1?'':'s'} and recent training.`:'Your training plan will adapt as you log RAWs.'}</p><div class="rings"><div class="ring">MOVE</div><div class="ring">TRAIN</div><div class="ring">GROW</div></div><div class="quickActions"><button class="primary autoBtn" id="surprise">🎲 AUTO</button><button class="primary fullBtn" id="fullBody">FULL BODY</button></div><div class="muted autoHint">AUTO chooses today's focus. Full Body balances upper push, upper pull, lower body, and core while favoring your most recovered areas.</div><button class="secondaryRec" id="auto">Start recommended ${rec}</button></div><h2>Choose a RAW</h2><div class="grid">${[['Push','Chest • shoulders • triceps'],['Pull','Back • biceps'],['Legs','Quads • hamstrings • calves'],['Core','Abs • trunk']].map(x=>`<button class="focus" data-start="${x[0]}"><strong>${x[0]}</strong><span>${x[1]}</span></button>`).join('')}</div><div class="card"><div class="sectionLabel">TARGET A MUSCLE GROUP</div><div class="row" style="margin-top:8px"><select id="muscle" class="grow">${muscles.map(x=>`<option>${x}</option>`).join('')}</select><button id="muscleGo">Generate</button></div></div><div class="card"><strong>Your Data</strong><p class="muted">RAW history stays on this device. Export a backup periodically.</p><div class="row"><button id="export">Export Backup</button><label><input id="import" type="file" accept="application/json" class="hidden"><button type="button" id="importBtn">Import Backup</button></label></div></div>`;$('#surprise').onclick=()=>start(recommended());$('#fullBody').onclick=startFullBody;$('#auto').onclick=()=>start(rec);app.querySelectorAll('[data-start]').forEach(b=>b.onclick=()=>start(b.dataset.start));$('#muscleGo').onclick=()=>start($('#muscle').value);$('#export').onclick=exportData;$('#importBtn').onclick=()=>$('#import').click();$('#import').onchange=importData}
function renderHistory(){const ss=[...state.sessions].filter(s=>s.completed).sort((a,b)=>b.date.localeCompare(a.date));$('#app').innerHTML=`<h2>RAW History</h2>${ss.length?ss.map(s=>`<div class="card"><strong>${s.target}</strong><div class="muted">${new Date(s.date).toLocaleDateString()} • ${s.entries.length} exercises</div>${s.entries.map(e=>{const x=exercises.find(z=>z.id===e.exerciseID);return `<div class="exercise"><strong>${x?.name||'Exercise'}</strong><div class="muted">${e.sets.map(a=>{const ex=x;return isBodyweight(ex)?`${a.reps} reps`:`${a.weight} lb × ${a.reps}`}).join(' • ')}</div></div>`}).join('')}</div>`).join(''):'<div class="card">No completed RAWs yet.</div>'}`}
function renderProgress(){const ss=state.sessions.filter(s=>s.completed),sets=ss.flatMap(s=>s.entries.flatMap(e=>e.sets)),vol=sets.reduce((n,s)=>n+(+s.weight||0)*(+s.reps||0),0),used=new Set(ss.flatMap(s=>s.entries.map(e=>e.exerciseID))).size;$('#app').innerHTML=`<h2>Progress</h2><div class="grid"><div class="card"><div class="stat">${ss.length}</div><div class="muted">RAWs</div></div><div class="card"><div class="stat">${used}</div><div class="muted">Exercises used</div></div><div class="card"><div class="stat">${Math.round(vol).toLocaleString()}</div><div class="muted">Total volume (lb)</div></div><div class="card"><div class="stat">${sets.length}</div><div class="muted">Sets logged</div></div></div><div class="card"><strong>Progression engine</strong><p>Complete all prescribed sets at 8+ reps and the next recommendation increases weight. Otherwise the app holds weight and asks you to improve reps.</p></div>`}
function exerciseHistory(id){return state.sessions.filter(s=>s.completed&&s.entries.some(e=>e.exerciseID===id)).sort((a,b)=>b.date.localeCompare(a.date)).map(s=>({date:s.date,entry:s.entries.find(e=>e.exerciseID===id)}))}
function setText(ex,set){return isBodyweight(ex)?`${set.reps||0} reps`:`${set.weight||0} lb × ${set.reps||0}`}
function renderExerciseDetail(id,q=''){const ex=exercises.find(e=>e.id===id);if(!ex)return renderLibrary(q);const h=exerciseHistory(id),last=h[0],weighted=!isBodyweight(ex),allSets=h.flatMap(x=>x.entry.sets||[]),bestWeight=weighted&&allSets.length?Math.max(...allSets.map(s=>+s.weight||0)):null,bestReps=allSets.length?Math.max(...allSets.map(s=>+s.reps||0)):0;$('#app').innerHTML=`<button class="small" id="backLibrary">‹ Library</button><div class="card hero"><div class="eyebrow">${ex.muscleGroup}</div><div class="heroTitle detailTitle">${ex.name}</div><div><span class="pill">${ex.function}</span><span class="pill">${ex.level}</span><span class="pill">${isBodyweight(ex)?'Bodyweight / reps':equip(ex.modality)}</span></div></div><div class="grid detailStats"><div class="card"><div class="stat">${h.length}</div><div class="muted">Times performed</div></div><div class="card"><div class="stat smallStat">${last?new Date(last.date).toLocaleDateString():'—'}</div><div class="muted">Last performed</div></div><div class="card"><div class="stat">${weighted?(bestWeight||'—'):(bestReps||'—')}</div><div class="muted">${weighted?'Best weight (lb)':'Best reps'}</div></div><div class="card"><div class="stat">${last?(last.entry.sets?.length||0):'—'}</div><div class="muted">Sets last time</div></div></div><h2>Performance History</h2>${h.length?h.map(x=>`<div class="card historyEntry"><div class="row"><strong>${new Date(x.date).toLocaleDateString()}</strong><span class="muted grow" style="text-align:right">${x.entry.sets?.length||0} sets</span></div><div class="historySets">${(x.entry.sets||[]).map((s,i)=>`<span class="pill">Set ${i+1}: ${setText(ex,s)}</span>`).join('')}</div></div>`).join(''):'<div class="card"><p>No RAW history for this exercise yet. Perform it in a RAW and its weight/reps history will appear here.</p></div>'}`;$('#backLibrary').onclick=()=>renderLibrary(q)}
function libraryResults(q=''){const filtered=exercises.filter(e=>(e.name+' '+e.muscleGroup+' '+e.level+' '+e.function).toLowerCase().includes(q.toLowerCase()));return filtered.map(e=>`<button class="card libraryCard" data-exercise="${e.id}"><span class="libraryName">${e.name}</span><span class="libraryMeta"><span class="pill">${e.muscleGroup}</span><span class="pill">${e.function}</span><span class="pill">${e.level}</span><span class="pill">${equip(e.modality)}</span></span><span class="chevron">›</span></button>`).join('')}
function bindLibraryCards(q=''){document.querySelectorAll('[data-exercise]').forEach(b=>b.onclick=()=>renderExerciseDetail(+b.dataset.exercise,q))}
function renderLibrary(q=''){const app=$('#app');app.innerHTML=`<h2>Exercise Library</h2><p class="muted">Select an exercise to view its progress and RAW history.</p><input id="search" class="search" placeholder="Search ${exercises.length} exercises" value="${q}" autocomplete="off" autocorrect="off" spellcheck="false"><div id="results">${libraryResults(q)}</div>`;const search=$('#search'),results=$('#results');search.addEventListener('input',()=>{const qNow=search.value;results.innerHTML=libraryResults(qNow);bindLibraryCards(qNow)});bindLibraryCards(q)}
function exportData(){const blob=new Blob([JSON.stringify(state,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`RAW-backup-${new Date().toISOString().slice(0,10)}.json`;a.click();URL.revokeObjectURL(a.href)}
function importData(ev){const f=ev.target.files[0];if(!f)return;const r=new FileReader();r.onload=()=>{try{const x=JSON.parse(r.result);if(!Array.isArray(x.sessions))throw Error();state=x;save();alert('Backup restored.');render()}catch{alert('That file is not a valid Workout Planner backup.')}};r.readAsText(f)}
document.querySelectorAll('.tabs button').forEach(b=>b.onclick=()=>{tab=b.dataset.tab;render()});fetch('exercises.json').then(r=>r.json()).then(x=>{exercises=x;render()}).catch(()=>{$('#app').innerHTML='<div class="card">Exercise library could not load. Serve this folder through a local or HTTPS web server rather than opening index.html directly.</div>'});if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js');
